services:
  app:
    container_name: "${PROJECT_NAME}_container"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONPATH=${PROJECT_ROOT}