name: python_r_env
channels:
  - defaults
dependencies:
  - python=3.11
  - r-base=3.6.1
  - r-essentials
  - python-dotenv
  - pandas
  - openpyxl
  - jupyter
  - python-docx
  - r-dotenv
  - scikit-learn
  - statsmodels

